title: Asher Krim - Software Engineer
email: krim.asher@gmail.com
description: "Asher Krim Software Engineer and Machine Learning Practitioner"

baseurl: "/"
url: "http://asherkrim.com"
#url: "http://localhost:4000"
github_username:  Krimit

name: Asher Krim

paginate: 5
paginate_path: /blog:num

permalink: pretty

markdown: kramdown
highlighter: rouge

plugins: [jekyll-paginate]